//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/localisation/LocalisationHello.msg.
//

#ifndef __INET_LOCALISATIONHELLO_M_H
#define __INET_LOCALISATIONHELLO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class WhereIam;
class AckitementFindMe;
class helloAnchor;
class helloTarget;
class CalculatedPos;
class AnchorData;
class EncryptedTargetData;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:23</tt> by opp_msgtool.
 * <pre>
 * class WhereIam extends FieldsChunk
 * {
 *     L3Address srcAddress;
 * }
 * </pre>
 */
class INET_API WhereIam : public ::inet::FieldsChunk
{
  protected:
    L3Address srcAddress;

  private:
    void copy(const WhereIam& other);

  protected:
    bool operator==(const WhereIam&) = delete;

  public:
    WhereIam();
    WhereIam(const WhereIam& other);
    virtual ~WhereIam();
    WhereIam& operator=(const WhereIam& other);
    virtual WhereIam *dup() const override {return new WhereIam(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getSrcAddress() const;
    virtual L3Address& getSrcAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<WhereIam*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const L3Address& srcAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WhereIam& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WhereIam& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:27</tt> by opp_msgtool.
 * <pre>
 * class AckitementFindMe extends FieldsChunk
 * {
 *     L3Address srcAddress;
 * 	//int rank;
 * }
 * </pre>
 */
class INET_API AckitementFindMe : public ::inet::FieldsChunk
{
  protected:
    L3Address srcAddress;

  private:
    void copy(const AckitementFindMe& other);

  protected:
    bool operator==(const AckitementFindMe&) = delete;

  public:
    AckitementFindMe();
    AckitementFindMe(const AckitementFindMe& other);
    virtual ~AckitementFindMe();
    AckitementFindMe& operator=(const AckitementFindMe& other);
    virtual AckitementFindMe *dup() const override {return new AckitementFindMe(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getSrcAddress() const;
    virtual L3Address& getSrcAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<AckitementFindMe*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const L3Address& srcAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckitementFindMe& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckitementFindMe& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:32</tt> by opp_msgtool.
 * <pre>
 * class helloAnchor extends FieldsChunk
 * {
 *     L3Address srcAddress;
 * }
 * </pre>
 */
class INET_API helloAnchor : public ::inet::FieldsChunk
{
  protected:
    L3Address srcAddress;

  private:
    void copy(const helloAnchor& other);

  protected:
    bool operator==(const helloAnchor&) = delete;

  public:
    helloAnchor();
    helloAnchor(const helloAnchor& other);
    virtual ~helloAnchor();
    helloAnchor& operator=(const helloAnchor& other);
    virtual helloAnchor *dup() const override {return new helloAnchor(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getSrcAddress() const;
    virtual L3Address& getSrcAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<helloAnchor*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const L3Address& srcAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const helloAnchor& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, helloAnchor& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:36</tt> by opp_msgtool.
 * <pre>
 * class helloTarget extends FieldsChunk
 * {
 *     L3Address srcAddress;
 * }
 * </pre>
 */
class INET_API helloTarget : public ::inet::FieldsChunk
{
  protected:
    L3Address srcAddress;

  private:
    void copy(const helloTarget& other);

  protected:
    bool operator==(const helloTarget&) = delete;

  public:
    helloTarget();
    helloTarget(const helloTarget& other);
    virtual ~helloTarget();
    helloTarget& operator=(const helloTarget& other);
    virtual helloTarget *dup() const override {return new helloTarget(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getSrcAddress() const;
    virtual L3Address& getSrcAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<helloTarget*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const L3Address& srcAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const helloTarget& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, helloTarget& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:40</tt> by opp_msgtool.
 * <pre>
 * class CalculatedPos extends FieldsChunk
 * {
 *     L3Address srcAddress;
 *     int rank;
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class INET_API CalculatedPos : public ::inet::FieldsChunk
{
  protected:
    L3Address srcAddress;
    int rank = 0;
    double x = 0;
    double y = 0;

  private:
    void copy(const CalculatedPos& other);

  protected:
    bool operator==(const CalculatedPos&) = delete;

  public:
    CalculatedPos();
    CalculatedPos(const CalculatedPos& other);
    virtual ~CalculatedPos();
    CalculatedPos& operator=(const CalculatedPos& other);
    virtual CalculatedPos *dup() const override {return new CalculatedPos(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getSrcAddress() const;
    virtual L3Address& getSrcAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<CalculatedPos*>(this)->getSrcAddress());}
    virtual void setSrcAddress(const L3Address& srcAddress);

    virtual int getRank() const;
    virtual void setRank(int rank);

    virtual double getX() const;
    virtual void setX(double x);

    virtual double getY() const;
    virtual void setY(double y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CalculatedPos& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CalculatedPos& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:47</tt> by opp_msgtool.
 * <pre>
 * class AnchorData extends FieldsChunk
 * {
 *     L3Address targetAddress;
 *     string encryptedMsg;
 *     string signature;
 *     int rank;
 * 
 *     double x;
 *     double y;
 * 
 * }
 * </pre>
 */
class INET_API AnchorData : public ::inet::FieldsChunk
{
  protected:
    L3Address targetAddress;
    ::omnetpp::opp_string encryptedMsg;
    ::omnetpp::opp_string signature;
    int rank = 0;
    double x = 0;
    double y = 0;

  private:
    void copy(const AnchorData& other);

  protected:
    bool operator==(const AnchorData&) = delete;

  public:
    AnchorData();
    AnchorData(const AnchorData& other);
    virtual ~AnchorData();
    AnchorData& operator=(const AnchorData& other);
    virtual AnchorData *dup() const override {return new AnchorData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getTargetAddress() const;
    virtual L3Address& getTargetAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<AnchorData*>(this)->getTargetAddress());}
    virtual void setTargetAddress(const L3Address& targetAddress);

    virtual const char * getEncryptedMsg() const;
    virtual void setEncryptedMsg(const char * encryptedMsg);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);

    virtual int getRank() const;
    virtual void setRank(int rank);

    virtual double getX() const;
    virtual void setX(double x);

    virtual double getY() const;
    virtual void setY(double y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AnchorData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AnchorData& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/localisation/LocalisationHello.msg:58</tt> by opp_msgtool.
 * <pre>
 * class EncryptedTargetData extends FieldsChunk
 * {
 *     L3Address targetAddress;
 *     string encryptedMsg;
 *     string signature;
 * 
 *     // Méthodes d'accès générées automatiquement par le compilateur
 * 
 * 
 * 
 * }
 * </pre>
 */
class INET_API EncryptedTargetData : public ::inet::FieldsChunk
{
  protected:
    L3Address targetAddress;
    ::omnetpp::opp_string encryptedMsg;
    ::omnetpp::opp_string signature;

  private:
    void copy(const EncryptedTargetData& other);

  protected:
    bool operator==(const EncryptedTargetData&) = delete;

  public:
    EncryptedTargetData();
    EncryptedTargetData(const EncryptedTargetData& other);
    virtual ~EncryptedTargetData();
    EncryptedTargetData& operator=(const EncryptedTargetData& other);
    virtual EncryptedTargetData *dup() const override {return new EncryptedTargetData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getTargetAddress() const;
    virtual L3Address& getTargetAddressForUpdate() { handleChange();return const_cast<L3Address&>(const_cast<EncryptedTargetData*>(this)->getTargetAddress());}
    virtual void setTargetAddress(const L3Address& targetAddress);

    virtual const char * getEncryptedMsg() const;
    virtual void setEncryptedMsg(const char * encryptedMsg);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EncryptedTargetData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EncryptedTargetData& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::WhereIam *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::WhereIam*>(ptr.get<cObject>()); }
template<> inline inet::AckitementFindMe *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::AckitementFindMe*>(ptr.get<cObject>()); }
template<> inline inet::helloAnchor *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::helloAnchor*>(ptr.get<cObject>()); }
template<> inline inet::helloTarget *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::helloTarget*>(ptr.get<cObject>()); }
template<> inline inet::CalculatedPos *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CalculatedPos*>(ptr.get<cObject>()); }
template<> inline inet::AnchorData *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::AnchorData*>(ptr.get<cObject>()); }
template<> inline inet::EncryptedTargetData *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::EncryptedTargetData*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_LOCALISATIONHELLO_M_H

